version: '2'

services:
  database:
    image: postgres:10
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_USER=sku-sub-service
      - POSTGRES_PASSWORD=sku-sub-service
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    ports:
      - 5432:5432